### ISSUE TITLE
Implement "Resume Preview" view

### ISSUE THREAD

**Issue by joel-alvarado** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#167] opened 2024-02-26 03:44 UTC
The "Resume Preview" view should display the final version of the resume in the selected template. There will be 4 buttons to "Download", "Send to a another user" and "Copy link". The 4th button "Save" will be used to save resume information and template from user account.

**Comment by irsaris** [comment] 2024-02-26 20:05
I believe this is a duplicate of #156

**Comment by joel-alvarado** [comment] 2024-02-26 21:03
Image reference for clarity
[image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/77513199/e3affe3a-8535-48eb-af88-28bd468d3c3f)

**Comment by irsaris** [comment] 2024-03-17 20:43
Hello, will the buttons be functional as well? Like have the functionality of actually downloading the pdf and such?

**Comment by irsaris** [comment] 2024-03-22 00:40
Reminder: this is due before midnight today.

**Closed** 2024-03-22 03:54 UTC
Labels: Preview Team
