### ISSUE TITLE
Implement profile page

### ISSUE THREAD

**Issue by Chosen-Juan1** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#122] opened 2024-02-25 23:05 UTC
This task involves implementing the page that represents the user's profile. In order to complete this task, the following must me completed:

- [x] Add the ability to display the a profile picture that represents the user.
- [x] Make sure the user's username is displayed under said picture in a way that resembles the mock-up
- [x] Add a button that allows the user to travel to the templates page and a one that allows the user to travel to the resume page
- [x] Add any other relevant information that may be recommended (like things that get added in the comments of this task).

The score of this task would be: Urgency (4) * Difficulty(5) = 20

**Comment by irsaris** [comment] 2024-02-26 20:41
duplicate of #110

**Comment by BreannaGSegarra** [comment] 2024-03-20 17:05
Not a duplicate; personal information page in the resume builder differs from profile page of the website.

**Comment by Chosen-Juan1** [comment] 2024-03-21 16:14
<img width="1440" alt="Screenshot 2024-03-21 at 12 11 06 PM" src="https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/101728824/a316fae7-1f41-4866-8dec-823ad3741e62">
This is the profile page, all buttons (except the user info page, as it does not exist at the moment) work. Made the UPResuMe logo (at the top left corner) work like a home button. Used the UPRM's logo as stand-in for the user's profile picture.

**Comment by Chosen-Juan1** [comment] 2024-03-21 16:16
The gap in the middle is for the resume gallery, a feature that will be elaborated in issue #123. Issue #124 will implement the sign out button.

**Closed** 2024-03-21 16:16 UTC
Labels: Data Entry Team

**Comment by Chosen-Juan1** [comment] 2024-03-21 20:29
The branch has been published under the name 'Profile'. It is ready for manager verification.
